[package]
name = "gshell"
version = "0.1.0"
edition = "2021"
# authors = "beef_e"
description = "Simple shell built for learning purposes"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
